project:
  type: website
  output-dir: ../_site

website:
  title: "Julia Things"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    grid:
      body-width: 1000px
      sidebar-width: 300px
      margin-width: 300px
    # css: styles.css
    toc: true
    html-math-method: mathjax
