name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.lycheeignore'
      - '.github/workflows/linkcheck.yml'

env:
  DIR: 'docs'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.x'
      - name: Cache python venv
        uses: actions/cache@v4
        if: ${{ contains(runner.name, 'GitHub Actions') }}
        id: cache-venv
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements-jb.txt') }}
          path: .venv
      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements-jb.txt
          echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
      - name: Check links
        run: jupyter-book build ${DIR} --builder linkcheck
